use_frameworks!

platform :ios, '8.0'

target 'ZbNavigationBarKit_Example' do
  pod 'ZbNavigationBarKit', :path => '../'

  target 'ZbNavigationBarKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
